{"time":"2025-02-23T14:13:16.0607147+01:00","level":"INFO","msg":"stream: starting","core version":"0.19.6","symlink path":"c:\\Users\\Cyril\\Desktop\\data-science-lab\\eyeball tracker\\wandb\\run-20250223_141313-imiytjxw\\logs\\debug-core.log"}
{"time":"2025-02-23T14:13:16.1890461+01:00","level":"INFO","msg":"created new stream","id":"imiytjxw"}
{"time":"2025-02-23T14:13:16.1890461+01:00","level":"INFO","msg":"stream: started","id":"imiytjxw"}
{"time":"2025-02-23T14:13:16.1890461+01:00","level":"INFO","msg":"handler: started","stream_id":"imiytjxw"}
{"time":"2025-02-23T14:13:16.1890461+01:00","level":"INFO","msg":"sender: started","stream_id":"imiytjxw"}
{"time":"2025-02-23T14:13:16.1890461+01:00","level":"INFO","msg":"writer: Do: started","stream_id":"imiytjxw"}
{"time":"2025-02-23T14:13:16.5551284+01:00","level":"INFO","msg":"Starting system monitor"}
{"time":"2025-02-23T16:36:08.296699+01:00","level":"INFO","msg":"api: retrying error","error":"Post \"https://api.wandb.ai/files/cyrilfrebel-none/eyeball%20tracker/imiytjxw/file_stream\": dial tcp 35.186.228.49:443: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond."}
{"time":"2025-02-23T16:36:11.1357391+01:00","level":"INFO","msg":"api: retrying error","error":"Post \"https://api.wandb.ai/graphql\": read tcp 192.168.0.171:61545->35.186.228.49:443: wsarecv: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond."}
{"time":"2025-02-23T16:36:31.8982992+01:00","level":"INFO","msg":"api: retrying error","error":"Post \"https://api.wandb.ai/files/cyrilfrebel-none/eyeball%20tracker/imiytjxw/file_stream\": dial tcp 35.186.228.49:443: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond."}
{"time":"2025-02-23T16:36:34.4784261+01:00","level":"INFO","msg":"api: retrying error","error":"Post \"https://api.wandb.ai/graphql\": dial tcp 35.186.228.49:443: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond."}
{"time":"2025-02-23T16:36:57.4798987+01:00","level":"INFO","msg":"api: retrying error","error":"Post \"https://api.wandb.ai/files/cyrilfrebel-none/eyeball%20tracker/imiytjxw/file_stream\": dial tcp 35.186.228.49:443: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond."}
{"time":"2025-02-23T16:36:59.9629979+01:00","level":"INFO","msg":"api: retrying error","error":"Post \"https://api.wandb.ai/graphql\": dial tcp 35.186.228.49:443: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond."}
{"time":"2025-02-23T16:37:26.8914503+01:00","level":"INFO","msg":"api: retrying error","error":"Post \"https://api.wandb.ai/files/cyrilfrebel-none/eyeball%20tracker/imiytjxw/file_stream\": dial tcp 35.186.228.49:443: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond."}
{"time":"2025-02-23T16:37:30.1023138+01:00","level":"INFO","msg":"api: retrying error","error":"Post \"https://api.wandb.ai/graphql\": dial tcp 35.186.228.49:443: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond."}
{"time":"2025-02-23T16:37:54.1015365+01:00","level":"INFO","msg":"api: retrying error","error":"Post \"https://api.wandb.ai/files/cyrilfrebel-none/eyeball%20tracker/imiytjxw/file_stream\": read tcp 192.168.0.171:62240->35.186.228.49:443: wsarecv: An existing connection was forcibly closed by the remote host."}
{"time":"2025-02-23T17:13:25.1692748+01:00","level":"INFO","msg":"Stopping system monitor"}
{"time":"2025-02-23T17:13:25.184067+01:00","level":"INFO","msg":"Stopped system monitor"}
{"time":"2025-02-23T17:13:26.2086213+01:00","level":"INFO","msg":"handler: operation stats","stats":{"operations":[{"desc":"updating run config","runtime_seconds":1.0309331}],"total_operations":1}}
{"time":"2025-02-23T17:13:31.2874103+01:00","level":"INFO","msg":"fileTransfer: Close: file transfer manager closed"}
{"time":"2025-02-23T17:13:32.6714528+01:00","level":"INFO","msg":"stream: closing","id":"imiytjxw"}
{"time":"2025-02-23T17:13:32.6714528+01:00","level":"INFO","msg":"handler: closed","stream_id":"imiytjxw"}
{"time":"2025-02-23T17:13:32.6715091+01:00","level":"INFO","msg":"writer: Close: closed","stream_id":"imiytjxw"}
{"time":"2025-02-23T17:13:32.673524+01:00","level":"INFO","msg":"sender: closed","stream_id":"imiytjxw"}
{"time":"2025-02-23T17:13:32.6741354+01:00","level":"INFO","msg":"stream: closed","id":"imiytjxw"}
