2025-02-28 23:15:27,743 INFO    MainThread:28252 [wandb_init.py:setup_run_log_directory():637] Logging user logs to c:\Users\Cyril\Desktop\data-science-lab\eyeball tracker\wandb\run-20250228_231527-ch3szg22\logs\debug.log
2025-02-28 23:15:27,744 INFO    MainThread:28252 [wandb_init.py:setup_run_log_directory():638] Logging internal logs to c:\Users\Cyril\Desktop\data-science-lab\eyeball tracker\wandb\run-20250228_231527-ch3szg22\logs\debug-internal.log
2025-02-28 23:15:27,744 INFO    MainThread:28252 [wandb_init.py:init():756] calling init triggers
2025-02-28 23:15:27,744 INFO    MainThread:28252 [wandb_init.py:init():761] wandb.init called with sweep_config: {}
config: {'epochs': 20, 'activation': 'relu', 'nb_layers': 3, 'nb_neurons': 128, 'dropout_rate': 0.1, 'optimizer': 'adam', 'loss': 'mae', 'metric': 'mae', 'augmentation': False, 'image_resize': 256, '_wandb': {}}
2025-02-28 23:15:27,745 INFO    MainThread:28252 [wandb_init.py:init():778] found existing run on stack: ssn1gxns
2025-02-28 23:15:27,745 INFO    MainThread:28252 [wandb_run.py:_finish():2110] finishing run cyrilfrebel-none/eyeball tracker/ssn1gxns
2025-02-28 23:15:28,108 INFO    MainThread:28252 [jupyter.py:save_history():458] not saving jupyter history
2025-02-28 23:15:28,108 INFO    MainThread:28252 [jupyter.py:save_ipynb():386] not saving jupyter notebook
2025-02-28 23:15:28,109 INFO    MainThread:28252 [wandb_init.py:_jupyter_teardown():571] cleaning up jupyter logic
2025-02-28 23:15:28,109 INFO    MainThread:28252 [wandb_run.py:_atexit_cleanup():2350] got exitcode: 0
2025-02-28 23:15:28,109 INFO    MainThread:28252 [wandb_run.py:_restore():2332] restore
2025-02-28 23:15:28,109 INFO    MainThread:28252 [wandb_run.py:_restore():2338] restore done
2025-02-28 23:15:30,068 INFO    MainThread:28252 [wandb_run.py:_footer_history_summary_info():3963] rendering history
2025-02-28 23:15:30,068 INFO    MainThread:28252 [wandb_run.py:_footer_history_summary_info():3995] rendering summary
2025-02-28 23:15:30,068 INFO    MainThread:28252 [wandb_run.py:_footer_sync_info():3924] logging synced files
2025-02-28 23:15:30,077 INFO    MainThread:28252 [wandb_init.py:init():789] starting backend
2025-02-28 23:15:30,077 INFO    MainThread:28252 [wandb_init.py:init():793] sending inform_init request
2025-02-28 23:15:30,096 INFO    MainThread:28252 [backend.py:_multiprocessing_setup():97] multiprocessing start_methods=spawn, using: spawn
2025-02-28 23:15:30,098 INFO    MainThread:28252 [wandb_init.py:init():808] backend started and connected
2025-02-28 23:15:30,103 INFO    MainThread:28252 [wandb_run.py:_label_probe_notebook():1196] probe notebook
2025-02-28 23:15:30,106 INFO    MainThread:28252 [wandb_init.py:init():901] updated telemetry
2025-02-28 23:15:30,109 INFO    MainThread:28252 [wandb_init.py:init():936] communicating run to backend with 90.0 second timeout
2025-02-28 23:15:30,500 INFO    MainThread:28252 [wandb_init.py:init():994] starting run threads in backend
2025-02-28 23:15:30,928 INFO    MainThread:28252 [wandb_run.py:_console_start():2385] atexit reg
2025-02-28 23:15:30,928 INFO    MainThread:28252 [wandb_run.py:_redirect():2235] redirect: wrap_raw
2025-02-28 23:15:30,928 INFO    MainThread:28252 [wandb_run.py:_redirect():2300] Wrapping output streams.
2025-02-28 23:15:30,928 INFO    MainThread:28252 [wandb_run.py:_redirect():2325] Redirects installed.
2025-02-28 23:15:30,929 INFO    MainThread:28252 [wandb_init.py:init():1036] run started, returning control to user process
