2025-03-01 14:34:30,071 INFO    MainThread:40440 [wandb_init.py:setup_run_log_directory():637] Logging user logs to c:\Users\Cyril\Desktop\data-science-lab\eyeball tracker\wandb\run-20250301_143430-1ndxkxg0\logs\debug.log
2025-03-01 14:34:30,071 INFO    MainThread:40440 [wandb_init.py:setup_run_log_directory():638] Logging internal logs to c:\Users\Cyril\Desktop\data-science-lab\eyeball tracker\wandb\run-20250301_143430-1ndxkxg0\logs\debug-internal.log
2025-03-01 14:34:30,072 INFO    MainThread:40440 [wandb_init.py:monkeypatch_ipython():589] configuring jupyter hooks <wandb.sdk.wandb_init._WandbInit object at 0x000002D2D55182E0>
2025-03-01 14:34:30,072 INFO    MainThread:40440 [wandb_init.py:init():756] calling init triggers
2025-03-01 14:34:30,072 INFO    MainThread:40440 [wandb_init.py:init():761] wandb.init called with sweep_config: {}
config: {'epochs': 250, 'activation': 'leaky_relu', 'nb_layers': 2, 'nb_neurons': 128, 'dropout_rate': 0.1, 'optimizer': 'adam', 'loss': <function euclidean_distance_loss at 0x000002D2E8B3A5E0>, 'metric': 'mae', 'augmentation': False, 'image_resize': 128, '_wandb': {}}
2025-03-01 14:34:30,072 INFO    MainThread:40440 [wandb_init.py:init():778] found existing run on stack: iz0hy1g5
2025-03-01 14:34:30,072 INFO    MainThread:40440 [wandb_run.py:_finish():2110] finishing run cyrilfrebel-none/eyeball tracker/iz0hy1g5
2025-03-01 14:34:30,074 INFO    MainThread:40440 [wandb_run.py:_atexit_cleanup():2350] got exitcode: 0
2025-03-01 14:34:30,074 INFO    MainThread:40440 [wandb_run.py:_restore():2332] restore
2025-03-01 14:34:30,074 INFO    MainThread:40440 [wandb_run.py:_restore():2338] restore done
2025-03-01 14:34:32,357 INFO    MainThread:40440 [wandb_run.py:_footer_history_summary_info():3963] rendering history
2025-03-01 14:34:32,358 INFO    MainThread:40440 [wandb_run.py:_footer_history_summary_info():3995] rendering summary
2025-03-01 14:34:32,359 INFO    MainThread:40440 [wandb_run.py:_footer_sync_info():3924] logging synced files
2025-03-01 14:34:32,372 INFO    MainThread:40440 [wandb_init.py:init():789] starting backend
2025-03-01 14:34:32,372 INFO    MainThread:40440 [wandb_init.py:init():793] sending inform_init request
2025-03-01 14:34:32,377 INFO    MainThread:40440 [backend.py:_multiprocessing_setup():97] multiprocessing start_methods=spawn, using: spawn
2025-03-01 14:34:32,383 INFO    MainThread:40440 [wandb_init.py:init():808] backend started and connected
2025-03-01 14:34:32,390 INFO    MainThread:40440 [wandb_run.py:_label_probe_notebook():1196] probe notebook
2025-03-01 14:34:32,666 INFO    MainThread:40440 [wandb_init.py:init():901] updated telemetry
2025-03-01 14:34:32,671 INFO    MainThread:40440 [wandb_init.py:init():936] communicating run to backend with 90.0 second timeout
2025-03-01 14:34:33,002 INFO    MainThread:40440 [wandb_init.py:init():994] starting run threads in backend
2025-03-01 14:34:33,606 INFO    MainThread:40440 [wandb_run.py:_console_start():2385] atexit reg
2025-03-01 14:34:33,607 INFO    MainThread:40440 [wandb_run.py:_redirect():2235] redirect: wrap_raw
2025-03-01 14:34:33,607 INFO    MainThread:40440 [wandb_run.py:_redirect():2300] Wrapping output streams.
2025-03-01 14:34:33,607 INFO    MainThread:40440 [wandb_run.py:_redirect():2325] Redirects installed.
2025-03-01 14:34:33,609 INFO    MainThread:40440 [wandb_init.py:init():1036] run started, returning control to user process
2025-03-01 14:35:12,182 INFO    MainThread:40440 [jupyter.py:save_ipynb():386] not saving jupyter notebook
2025-03-01 14:35:12,182 INFO    MainThread:40440 [wandb_init.py:_pause_backend():554] pausing backend
2025-03-01 14:35:28,293 INFO    MainThread:40440 [wandb_init.py:_resume_backend():559] resuming backend
2025-03-01 14:35:28,299 INFO    MainThread:40440 [jupyter.py:save_ipynb():386] not saving jupyter notebook
2025-03-01 14:35:28,299 INFO    MainThread:40440 [wandb_init.py:_pause_backend():554] pausing backend
2025-03-01 14:35:29,815 INFO    MainThread:40440 [wandb_init.py:_resume_backend():559] resuming backend
2025-03-01 14:35:29,820 INFO    MainThread:40440 [jupyter.py:save_ipynb():386] not saving jupyter notebook
2025-03-01 14:35:29,820 INFO    MainThread:40440 [wandb_init.py:_pause_backend():554] pausing backend
2025-03-01 14:35:34,191 INFO    MainThread:40440 [wandb_init.py:_resume_backend():559] resuming backend
2025-03-01 14:35:34,194 INFO    MainThread:40440 [jupyter.py:save_ipynb():386] not saving jupyter notebook
2025-03-01 14:35:34,195 INFO    MainThread:40440 [wandb_init.py:_pause_backend():554] pausing backend
2025-03-01 14:35:35,698 INFO    MainThread:40440 [wandb_init.py:_resume_backend():559] resuming backend
2025-03-01 14:35:35,703 INFO    MainThread:40440 [jupyter.py:save_ipynb():386] not saving jupyter notebook
2025-03-01 14:35:35,703 INFO    MainThread:40440 [wandb_init.py:_pause_backend():554] pausing backend
2025-03-01 14:35:35,893 INFO    MainThread:40440 [wandb_init.py:_resume_backend():559] resuming backend
2025-03-01 14:35:35,905 INFO    MainThread:40440 [wandb_init.py:setup_run_log_directory():637] Logging user logs to c:\Users\Cyril\Desktop\data-science-lab\eyeball tracker\wandb\run-20250301_143535-eqya8llm\logs\debug.log
2025-03-01 14:35:35,905 INFO    MainThread:40440 [wandb_init.py:setup_run_log_directory():638] Logging internal logs to c:\Users\Cyril\Desktop\data-science-lab\eyeball tracker\wandb\run-20250301_143535-eqya8llm\logs\debug-internal.log
2025-03-01 14:35:35,905 INFO    MainThread:40440 [wandb_init.py:init():756] calling init triggers
2025-03-01 14:35:35,905 INFO    MainThread:40440 [wandb_init.py:init():761] wandb.init called with sweep_config: {}
config: {'epochs': 20, 'activation': 'leaky_relu', 'nb_layers': 2, 'nb_neurons': 128, 'dropout_rate': 0.1, 'optimizer': 'adam', 'loss': <function euclidean_distance_loss at 0x000002D2E6229DC0>, 'metric': 'mae', 'augmentation': False, 'image_resize': 128, '_wandb': {}}
2025-03-01 14:35:35,906 INFO    MainThread:40440 [wandb_init.py:init():778] found existing run on stack: 1ndxkxg0
2025-03-01 14:35:35,906 INFO    MainThread:40440 [wandb_run.py:_finish():2110] finishing run cyrilfrebel-none/eyeball tracker/1ndxkxg0
2025-03-01 14:35:35,907 INFO    MainThread:40440 [jupyter.py:save_history():458] not saving jupyter history
2025-03-01 14:35:35,907 INFO    MainThread:40440 [jupyter.py:save_ipynb():386] not saving jupyter notebook
2025-03-01 14:35:35,908 INFO    MainThread:40440 [wandb_init.py:_jupyter_teardown():571] cleaning up jupyter logic
2025-03-01 14:35:35,908 INFO    MainThread:40440 [wandb_run.py:_atexit_cleanup():2350] got exitcode: 0
2025-03-01 14:35:35,908 INFO    MainThread:40440 [wandb_run.py:_restore():2332] restore
2025-03-01 14:35:35,909 INFO    MainThread:40440 [wandb_run.py:_restore():2338] restore done
2025-03-01 14:35:38,335 INFO    MainThread:40440 [wandb_run.py:_footer_history_summary_info():3963] rendering history
2025-03-01 14:35:38,335 INFO    MainThread:40440 [wandb_run.py:_footer_history_summary_info():3995] rendering summary
2025-03-01 14:35:38,336 INFO    MainThread:40440 [wandb_run.py:_footer_sync_info():3924] logging synced files
